### ISSUE TITLE
Get containerization / local reproducibility

### ISSUE THREAD

**Issue by choccydev** [nodoambiental/portal-jekyll#25]
# Build reproducibility is needed here

This issue resides in the current frailty of the Jekyll ecosystem. As of now, a _lot_ of libs and projects became abandonware, which means that updating dependencies is bound to break something in a hard or impossible to fix way.

Currently, the build is completely broken in local copies of the repo, due to incompatibilities between some dependencies used by the project, culprits mainly being bibliography support and markdown parsing.

## What we can do to fix this

An option is to containerize the project under docker, to limit and restrict the exact versions used currently in the production server. 

Another option is to employ a build system that favours reproducible builds, as Bazel or something Starlark-y, more so given that there are going to be introduced some extra steps in the compilation, mainly to source files that need to be procedurally generated.

**Comment by choccydev** [comment]
Not to mention the current Ruby version in use (`2.5.1p57`) is `EOL` and a security risk.

**Comment by choccydev** [comment]
It would be quicker to containerize the system, but it might introduce extra complexity when adding the "plug-ins" to source procedurally generated files. I suggest opting into adding a reproducible build system, as mentioned in the original post.

Suggestions open. @maordano?

**Comment by maordano** [comment]
I agree.
